### ISSUE TITLE
Please add more descriptions for your files or codes. It's hard to understand what's your every code file for.

### ISSUE THREAD

**Issue by rmhsawyer** [Arshitha/Entertainment-Tracking-system#9]
Not matter in the Front End or Back end directory, or master page there is almost no file or directory description. It's not readable and translatable. And there is also not enough comments for your source codes to show your web module.

**Comment by Arshitha** [comment]
Hi, 
Thanks for your review. The readme.md file has been updated with information about each directory to make it more readable for others. 
Thanks!
